@hostname = http://localhost:8000

### Create one transport. Input info is json with string 'type' and string 'plate'. 
### Type must be from TransportType (transports/transports.constants.ts)
post {{hostname}}/transports
Content-Type: application/json

{
    "type": "m",
    "plate": "AC562D144"
}

### Get one transport by plate. Input info is param @getplate
@getplate = AC562D144
get {{hostname}}/transports/{{getplate}}

### Get all transports
get {{hostname}}/transports

### Retrieve one transport. Input info is param @retrieve
@retrieve = AC562D144
delete {{hostname}}/transports/{{retrieve}}